import { Button3DConfig } from '../types/buttons3d';

export const BUTTONS_3D_CATALOG: Button3DConfig[] = [
  {
    id: 'btn-cyber-circuit',
    name: 'Cyber Circuit Ignition',
    tagline: 'Circuito PCB negro con pistas conductoras de neón y chip central',
    textureType: 'cyberCircuit',
    shape: 'round',
    behavior: 'momentary',
    primaryColor: '#080c14',
    glowColor: '#06b6d4',
    icon: 'zap',
    pressDepth: 0.18,
    soundPitch: 1.2,
  },
  {
    id: 'btn-carbon-toggle',
    name: 'Carbon Fiber Switch',
    tagline: 'Tejido twill de fibra de carbono aeroespacial con bisel de aluminio',
    textureType: 'carbonFiber',
    shape: 'square',
    behavior: 'toggle',
    primaryColor: '#1a1d24',
    glowColor: '#f97316',
    icon: 'power',
    pressDepth: 0.22,
    soundPitch: 0.85,
  },
  {
    id: 'btn-brushed-titanium',
    name: 'Brushed Titanium Tactile',
    tagline: 'Aleación de titanio con micro-estrías circulares y reflejos anisotrópicos',
    textureType: 'brushedTitanium',
    shape: 'hexagon',
    behavior: 'momentary',
    primaryColor: '#94a3b8',
    glowColor: '#a855f7',
    icon: 'cpu',
    pressDepth: 0.16,
    soundPitch: 1.4,
  },
  {
    id: 'btn-frosted-glass',
    name: 'Frosted Crystal Glass',
    tagline: 'Vidrio esmerilado translúcido con dispersión cáustica y retroiluminación',
    textureType: 'frostedGlass',
    shape: 'pill',
    behavior: 'toggle',
    primaryColor: '#e0f2fe',
    glowColor: '#38bdf8',
    icon: 'sparkles',
    pressDepth: 0.20,
    soundPitch: 1.6,
  },
  {
    id: 'btn-marble-gold',
    name: 'Cerámica Mármol & Oro',
    tagline: 'Mármol blanco Carrara de alta gama con fracturas de oro pulido',
    textureType: 'marbleGold',
    shape: 'round',
    behavior: 'momentary',
    primaryColor: '#f8fafc',
    glowColor: '#eab308',
    icon: 'shield',
    pressDepth: 0.17,
    soundPitch: 1.0,
  },
  {
    id: 'btn-arcade-jelly',
    name: 'Arcade Jelly Dome',
    tagline: 'Cúpula de resina de goma semitransparente con rebote arcade retro',
    textureType: 'arcadeJelly',
    shape: 'round',
    behavior: 'momentary',
    primaryColor: '#db2777',
    glowColor: '#ec4899',
    icon: 'rocket',
    pressDepth: 0.24,
    soundPitch: 0.9,
  },
  {
    id: 'btn-hologram-glitch',
    name: 'Holo-Glitch Projector',
    tagline: 'Interruptor holográfico con barrido de scanlines y dispersión digital',
    textureType: 'hologramGlitch',
    shape: 'hexagon',
    behavior: 'toggle',
    primaryColor: '#0f172a',
    glowColor: '#10b981',
    icon: 'radio',
    pressDepth: 0.18,
    soundPitch: 1.3,
  },
];
